import { type NextPage } from "next";
import Head from "next/head";

const PageHead = () => (
  <Head>
    <title>Create T3 App</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

const Home: NextPage = () => {
  return (
    <>
      <PageHead />
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16"></div>
      </main>
    </>
  );
};

export default Home;
